"""
Django settings for gotoworkamerica project.

Generated by 'django-admin startproject' using Django 3.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os
import datetime
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-5&hl1gzo9p+e-p17fy&gds-&ol3$y5exrk7&cn_a4e$=(y!@&v'

#Site URL
SITE_URL = 'http://localhost:8080'

#Site Name
SITE_NAME = 'Go To Work America'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

AUTH_USER_MODEL = 'accountapp.User'

# Application definition
#  gunicorn --bind 0.0.0.0:8080 gotoworkamerica.wsgi
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'django_db_logger',
    'tracking',
    'select2',
    'rest_framework',
    'rest_framework.authtoken',
    'fcm_django',
    'django_celery_beat',
    'backendapp',
    'accountapp',
    'jobapp',
    'apiapp',
    'blogapp',
    'ckeditor',
    'ckeditor_uploader',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'tracking.middleware.VisitorTrackingMiddleware',
]

ROOT_URLCONF = 'gotoworkamerica.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'gotoworkamerica.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'gotoworkamerica_db',
#         'USER': 'gtwa',
#         'PASSWORD': 'gtwa@2021',
#         'HOST': '127.0.0.1',
#         'PORT': '5432',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'go_to_america',
        'USER': 'postgres',
        'PASSWORD': 'go_to_america',
        'HOST': '127.0.0.1',
        'PORT': '5432',
    }
}
# psql -- username=go_to_america
# ALTER TABLE public.<table_name> OWNER TO go_to_america;





# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL          = '/static/'
STATICFILES_DIRS    = ( os.path.join(BASE_DIR, 'static'),)
STATIC_ROOT         = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#Tracking Settings
TRACK_AJAX_REQUESTS         = True
TRACK_ANONYMOUS_USERS       = True
TRACK_SUPERUSERS            = False
TRACK_PAGEVIEWS             = True
TRACK_REFERER               = True
TRACK_QUERY_STRING          = True
TRACK_IGNORE_STATUS_CODES   = [400, 404, 403, 405, 410, 500]

#LOGGING Settings
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "%(levelname)s %(asctime)s %(module)s %(process)d %(thread)d %(message)s"
        },
        "simple": {"format": "%(levelname)s %(asctime)s %(message)s"},
    },
    "handlers": {
        "db_log": {
            "level": "DEBUG",
            "class": "django_db_logger.db_log_handler.DatabaseLogHandler",
        }
    },
    "loggers": {
        "django.request": {"handlers": ["db_log"], "level": "DEBUG", "propagate": True},
        "django_auth": {"handlers": ["db_log"], "level": "DEBUG", "propagate": False},
        "accountapp": {"handlers": ["db_log"], "level": "DEBUG", "propagate": False},
        "backendapp": {"handlers": ["db_log"], "level": "DEBUG", "propagate": False},
        "apiapp": {"handlers": ["db_log"], "level": "DEBUG", "propagate": False},
    },
}
#per page display records
PER_PAGE_RECORD = 20

#SMTP Settings
EMAIL_HOST           = 'smtp.gmail.com'
EMAIL_HOST_USER      = 'notionmind.dev@gmail.com'
EMAIL_HOST_PASSWORD  = 'Test@1234'
EMAIL_PORT           = 587
EMAIL_USE_TLS        = True
DEFAULT_FROM_EMAIL  = "GoToWorkAmerica <no_reply@gotoworkamerica.com>"
EMAIL_BACKEND       = "django.core.mail.backends.smtp.EmailBackend"


DATA_UPLOAD_MAX_NUMBER_FIELDS   = 10240
DATA_UPLOAD_MAX_MEMORY_SIZE     = 10485760  # bytes
TOO_MANY_FIELDS_MSG = (
    "The number of GET/POST parameters exceeded settings.DATA_UPLOAD_MAX_NUMBER_FIELDS."
)
TOO_MUCH_DATA_MSG = "Request body exceeded settings.DATA_UPLOAD_MAX_MEMORY_SIZE."

TOKEN_EXPIRE_PERIOD = datetime.timedelta(minutes=1440) #positive integer value of minutes after which the token expires

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES' : (
        'apiapp.authentication.ExpireTokenAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'apiapp.permissions.hasKey',
        'rest_framework.permissions.IsAuthenticated',
    )
}
#Twilio API KEY
ACCOUNT_SECURITY_API_KEY    ='3720ba80a0d6f4b25636f735e4328e75'
TWILIO_ACCOUNT_SID          ='ACb3830fd635214c087e06eb5c88962d9c'
TWILIO_AUTH_TOKEN           ='eb9d7d858d4201e1f3727ffd9a9c442e'
TWILIO_PHONE_NUMBER         ='+12569523641'

#GOOGLE API KEY for MAP View or Find Latlong
GOOGLE_API_KEY              = 'AIzaSyCl7cufNxnnkibg5zL0lnbsryDQRbwakc4'
GOOGLE_RECAPTCHA_SITE_KEY   = '6LeB7rUaAAAAAMiqMaW5wLBwWur-7cq9NI919OJj'
GOOGLE_RECAPTCHA_SECRET_KEY = '6LeB7rUaAAAAAGwQ9C7-U73Yy3Xe2JopBB8kq-u1'

FCM_DJANGO_SETTINGS = {
    "FCM_SERVER_KEY": "AAAAMAanpsg:APA91bE_oL2FgpW0H6VWsu8-QV4eUYddiw5fCtHB5fdUAJeU6r1aDnXmawVfrfKeXruDLVe9EZmD7b-rAfZYPYC74Bc_7la_rgYNC12JRyOi6e7PVajqES2XAVIRduhDDBZZFP1s4JmX"
}

#CKEDITOR Settings
CKEDITOR_UPLOAD_PATH = 'uploads/'
CKEDITOR_IMAGE_BACKEND = "pillow"

# Stripe
STRIPE_SECRET_KEY       = 'sk_test_51I8u1ZLFsKfj1mLroXfZ0VhiALWgXdnHXstJKW6rltVAOPpRTKlfds1JyFMTxMJsyBWlNedysPx6iulwEDWQJ0ra009rA4SPEn'
STRIPE_PUBLISHABLE_KEY  = 'pk_test_51I8u1ZLFsKfj1mLrFK9EQA3JMqwYZ6Gh1EGFC1fTZvKl1rz50hOsOJvm27DZ30vHOinIrcE65a41PnY8XGM1VSLQ00FuhVu21j'
STRIPE_WEBHOOK_SECRET   = "whsec_NKAhATpPKORdNPgvFNVucZK6XTQpFxXX"
