<<<<<<< HEAD
# Generated by Django 3.2.5 on 2021-12-03 21:43
=======
# Generated by Django 3.2.5 on 2021-12-24 20:02
>>>>>>> main

import autoslug.fields
import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import select2.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/images/')),
                ('title', models.CharField(max_length=255)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='title', unique=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('featured', models.BooleanField(default=False)),
                ('publish', models.BooleanField(default=False)),
                ('ipaddress', models.GenericIPAddressField(blank=True, null=True)),
                ('source', models.CharField(blank=True, choices=[('IOS', 'IOS'), ('Android', 'Android'), ('Web', 'Web')], max_length=10, null=True)),
                ('browserinfo', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
            },
        ),
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name', unique=True)),
                ('publish', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='BlogView',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ipaddress', models.GenericIPAddressField(blank=True, null=True)),
                ('source', models.CharField(choices=[('IOS', 'IOS'), ('Android', 'Android'), ('Web', 'Web')], default='Web', max_length=10)),
                ('browserinfo', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogapp.blog')),
                ('user', select2.fields.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'View',
                'verbose_name_plural': 'Views',
            },
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('ipaddress', models.GenericIPAddressField(blank=True, null=True)),
                ('source', models.CharField(choices=[('IOS', 'IOS'), ('Android', 'Android'), ('Web', 'Web')], default='Web', max_length=10)),
                ('browserinfo', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogapp.blog')),
                ('user', select2.fields.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogapp.blogcategory'),
        ),
        migrations.AddField(
            model_name='blog',
            name='createdBy',
            field=select2.fields.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
