# Generated by Django 3.2.5 on 2021-12-03 21:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIAuthKey',
            fields=[
                ('key', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('isRevoked', models.BooleanField(default=False)),
                ('ipaddress', models.GenericIPAddressField(blank=True, null=True)),
                ('browserinfo', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedAt', models.DateTimeField(auto_now=True, null=True)),
                ('createdBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Auth Key',
                'verbose_name_plural': 'API Auth Keys',
            },
        ),
    ]
